### ISSUE TITLE
Non-existent class: Zend

### ISSUE THREAD

**Issue by gutasaputra** [desta88/Codeigniter-Barcode#2]
hello there, i have some issue with your library.
when i tried to show my barcode, i got error like this  

> Non-existent class: Zend

please tell me what to do.

im using codeigniter v 3.05
zend framework v 2.49

thanks

**Comment by desta88** [comment]
Hai man, 
Do you've to load your library into controller?

**Comment by gutasaputra** [comment]
halo @desta88 

yes of course.
btw i already fix this issue.
the problem is on the zend class.
all you need to is go to zend library, and change the name into zend.

**Comment by desta88** [comment]
Great @gutasaputra,

But, What do you mean change the class of name? or? 
I'm must to try before

Thanks for your contribution..

**Comment by gutasaputra** [comment]
i download brand new zend lib. when i open those file, the class name is CI_Zend,
thats why codeigniter will tell you this error : Non-existent class: Zend

when i change the class name into zend. 
everything work perfectly fine.

**Comment by desta88** [comment]
Hay @gutasaputra

I think the issue is differences zend library version betwen you and me,
I dont know it would be work on Codeigniter 2 or not?

But ASAP I'll try to your library and must work in Codeigniter 2
(You know in Indonesia Codeigniter 2 still familiar :ghost: )

Thanks for your contribution bro.. :+1:

**Comment by workeywebworks** [comment]
I do have the same problem the Zend library says Non-consistent class, I just rename the Zend class into Zend instead of CI_Zend..

Thank you man
