### ISSUE TITLE
I Wouldn't call this a issue just a question

### ISSUE THREAD

**Issue by YosefOberlander** [desta88/Codeigniter-Barcode#6]
How can i save the rendered barcode to a variable so only where i echo that var the barcode will display

**Comment by desta88** [comment]
just like in example, or like this :  

$var = 123456789;
$this->set_barcode($var);

**Comment by YosefOberlander** [comment]
Ok let me better explain when I pass the barcode into the view and I  load the page the only thing what gets displayed is an image with the barcode and a black background I don't want that I want for the view to get loading and pass the barcode in an HTML <img /> tag  like the image below 
![screencapture-localhost-techwise-search-find_rma_authorization-1498028345372](https://user-images.githubusercontent.com/20997717/27371176-a5e06232-562d-11e7-8a31-77f59761916e.png)
