### ISSUE TITLE
Module load error

### ISSUE THREAD

**Issue by ii64** [desta88/Codeigniter-Barcode#9]
Hi, I used Codeigniter 3, at the first try to load the module it got error like #2, loved it but still failed to load the module? is you guys already solved this error too or it just from my side that use CI 3?

![image](https://user-images.githubusercontent.com/26342994/51986855-c139c980-24d3-11e9-91c2-b480e853dabb.png)

**Comment by destaFog** [comment]
Have you put the library in the right place?

**Comment by ii64** [comment]
Yes i did put it on application/libraries.
The Zend framework is also installed on the root dir

![image](https://user-images.githubusercontent.com/26342994/52043539-8cc91a80-2572-11e9-9aa2-c5ade2905fe4.png)

**Comment by ii64** [comment]
Case Closed
